import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  az: {
    settings: "Parametrlər",
    customize: "Görünüşü və interfeysi fərdiləşdirin",
    vinylSettings: "Vinyl Tənzimləmələri",
    hideVinylAll: "Vinyl-ı tamamilə gizlə",
    hideVinylArtist: "Yalnız Artist səhifəsində gizlə",
    contentView: "Məzmun Görünüşü",
    biggerText: "Böyük Mətn",
    biggerCursor: "Böyük Kursor",
    lineHeight: "Sətir Hündürlüyü",
    lineNormal: "Normal",
    lineRelaxed: "Rahat",
    lineLoose: "Geniş",
    effectsColors: "Effektlər və Rənglər",
    stopAnimations: "Animasiyaları Dayandır",
    invertColors: "Rəngləri Çevir",
    brightness: "Parlaqlıq",
    contrast: "Kontrast",
    language: "Dil",
    theme: "Görünüş Rejimi",
    dark: "Qaranlıq",
    light: "İşıqlı",
    reset: "Parametrləri Sıfırla",
    addToCart: "Səbətə əlavə et",
    back: "Geri",
    description: "Təsvir",
    tracklist: "Mahnı Siyahısı",
    reviews: "Rəylər və Suallar",
    genre: "Janr",
    selectDesign: "Dizayn Seçin",
    selected: "Seçilmiş",
    quantity: "Miqdar",
    notFound: "Albom Tapılmadı",
    backHome: "Ana səhifəyə qayıt",
    images: "Şəkillər",
    imageNotLoaded: "Şəkil yüklənmədi",
    animated: "Animasiya",
    static: "Statik",
    submitReview: "Paylaş",
    submitQuestion: "Sualı Göndər",
    writeReview: "Rəyinizi yazın...",
    writeQuestion: "Sualınızı yazın...",
    leaveReview: "Rəy Bildir",
    askQuestion: "Sual Ver",
    reply: "Cavabla",
    replyPlaceholder: "Cavabınız...",
    send: "Göndər",
    // Nav
    navNew: "Yeni Gələnlər",
    navGenres: "Janrlar",
    navOrders: "Sifariş",
    navAbout: "Haqqımızda",
    // Hero
    heroTag: "Premium Vinyl Kolleksiyası",
    heroNew: "YENI!",
    heroDesc: '"xperiment" amerikalı reper və müğənni Ken Carsonun yeni studiya albomudur.',
    shopNow: "İndi alış-veriş edin",
    listenPreview: "Dinləmə Önizləməsi",
    statVinyl: "Vinyl",
    statRare: "Nadir Preslər",
    statGenres: "Janrlar",
    // Featured albums
    newThisWeek: "Bu Həftə Yeni",
    featuredRecords: "Seçilmiş Yazılar",
    viewAllCollection: "Bütün Kolleksiyaya Baxın",
    newBadge: "YENI",
    // Genre section
    explore: "Araşdırın",
    browseByGenre: "Janra görə axtarış",
    recordsWord: "yazı",
    // Merch promo
    officialMerch: "Rəsmi Merch",
    merchSubtitle: "Artist geyimləri və kolleksiya əşyaları",
    merchStore: "Merch Mağazası",
    exclusiveMerch: "Eksklüziv Merch Kolleksiyaları",
    merchCtaSubtitle: "Sevimli artistlərindən original geyim və aksessuarlar",
    buyNow: "İndi Al",
    // Accessories
    accessoriesTitle: "Avadanlıq və Aksessuarlar",
    accessoriesSubtitle: "Vinyl kolleksiyanız üçün hər şey",
    viewAll: "Hamısına bax",
    outOfStock: "Tükənib",
    catAll: "Hamısı",
    catTurntable: "Pikap",
    catCdPlayer: "CD Pleyer",
    catStorage: "Saxlama",
    catCleaning: "Təmizlik",
    catAccessories: "Aksessuarlar",
    // Newsletter
    newsletterTag: "Yeniliklərdən xəbərdar olun",
    newsletterTitle: "Backrooms bülleteninə qoşulun",
    newsletterSubtitle: "Spam olmadan yeni buraxılışlara, nadir tapıntılara və xüsusi endirimlərə eksklüziv giriş əldə edin.",
    emailPlaceholder: "Email daxil edin",
    subscribe: "Abunə olun",
    newsletterNote: "Klubda artıq 10.000+ vinil abunəçisinə qoşulun",
    // Footer
    footerShop: "Mağaza",
    footerGenres: "Janrlar",
    footerSupport: "Dəstək",
    footerCompany: "Şirkət",
    footerNewArrivals: "Yeni Gəlişlər",
    footerBestSellers: "Ən çox Satılanlar",
    footerPreOrders: "Əvvəlcədən Sifarişlər",
    footerSale: "Satış",
    footerContact: "Bizimlə Əlaqə",
    footerShipping: "Göndərmə Məlumatı",
    footerReturns: "Qaytarılmalar",
    footerFaq: "Tez-Tez verilən suallar",
    footerAbout: "Haqqımızda",
    footerCareers: "Karyeralar",
    footerBlog: "Bloq",
    footerTagline: "Premium vinil valları üçün məkanınız. Musiqini eşitmək üçün nəzərdə tutulduğu kimi yaşayın.",
    footerRights: "© 2026 Backrooms. Bütün hüquqlar qorunur.",
    privacyPolicy: "Məxfilik Siyasəti",
    termsOfService: "Xidmət Şərtləri",
    // Cart
    cart: "Səbət",
    cartEmpty: "Səbət boşdur",
    viewCart: "Səbətə bax",
    maxQuantityReached: "Bir məhsuldan maksimum 4 ədəd əlavə etmək olar",
    quantityLimitNote: "Hər müştəri üçün limit: bir məhsuldan maksimum 4 ədəd",
    orderSummary: "Sifariş xülasəsi",
    total: "Cəmi:",
    checkout: "Ödənişə keç",
    continueShopping: "Alış-verişə davam et",
    // Album page
    selectDesignWarning: "⚠️ Zəhmət olmasa dizayn seçin",
    tracklistLoading: "Mahnı siyahısı yüklənir...",
    tracklistUnavailable: "Mahnı siyahısı hazırda əlçatan deyil.",
    productUnavailable: "Bu məhsul hələ onlayn satışda deyil",
    subscribedToast: "Abunə oldunuz! ✓",
    adding: "Əlavə edilir...",
    addedToCart: "Səbətə əlavə edildi! ✓",
    errorTryAgain: "Xəta baş verdi. Yenidən cəhd edin.",
    shopifyIdMissing: "Shopify məhsul ID-si tapılmadı",
    recommendedProducts: "Tövsiyə Edilən Məhsullar",
    // Collections
    allCollection: "Bütün Kolleksiya",
    discoverRecords: "vinil qeydimizi kəşf edin",
    filterByGenre: "Janra görə filtr:",
    filterByYear: "İlə görə filtr:",
    filterByArtist: "İfaçıya görə filtr:",
    sortByPrice: "Qiymətə görə sırala:",
    all: "Hamısı",
    sortNone: "Standart",
    sortCheap: "Ucuzdan Bahaya",
    sortExpensive: "Bahadan Ucuza",
    // Artist page
    artistNotFound: "Artist Tapılmadı",
    latestRelease: "Son Buraxılış",
    discography: "Diskografiya",
    music: "Musiqi",
    // Search
    searchPlaceholder: "Albom, artist və ya janr axtar...",
    searchPlaceholderShort: "Albom və ya artist axtar...",
    resultsFor: '"{query}" üçün nəticələr',
    allAlbums: "Bütün albomlar",
    resultsWord: "nəticə",
    noResults: "Heç bir nəticə tapılmadı",
    tryDifferent: "Başqa açar söz və ya janr sınayın",
    similarGenres: "Oxşar janrlar",
    viewAllResults: "Bütün nəticələrə bax →",
    // Favorites
    loading: "Yüklənir...",
    favoritesTitle: "Sevimlilər",
    albumsWord: "albom",
    noFavoritesYet: "Hələ sevimli yoxdur",
    addFavoritesHint: "Bəyəndiyiniz albomları sevimlilərinizə əlavə edin",
    // User menu
    orders: "Sifarişlər",
    logout: "Çıxış",
    close: "Bağla",
    // 404
    pageNotFound: "Oops! Səhifə tapılmadı",
    // Merch collections page
    merchCollection: "Merch Kolleksiyası",
    categoriesWord: "kateqoriya",
    artistsWord: "ifaçı",
    productsFound: "Məhsul tapıldı",
    backToCategories: "Kateqoriyalara qayıt",
    productsWord: "Məhsul",
    viewCollection: "Kolleksiyaya Bax",
    moreWord: "daha",
    filters: "Filtrlər",
    clear: "Təmizlə",
    artistLabel: "İfaçı",
    yearLabel: "İl",
    sortLabel: "Sırala",
    sortDefault: "Standart",
    priceLowHigh: "Qiymət: Azdan Çoxa",
    priceHighLow: "Qiymət: Çoxdan Aza",
    yearNewOld: "İl: Yenidən Köhnəyə",
    yearOldNew: "İl: Köhnədən Yeniyə",
    noProductsFound: "Heç bir məhsul tapılmadı",
    clearFilters: "Filtrləri Təmizlə",
    // Merch product page
    productNotFound: "Məhsul Tapılmadı",
    backToMerch: "← Merch səhifəsinə qayıt",
    selectSize: "Ölçü Seçin",
    selectSizeWarning: "⚠️ Zəhmət olmasa ölçüsü seçin",
    colorLabel: "Rəng",
    productDetails: "Məhsul Məlumatları",
    categoryLabel: "Kateqoriya:",
    releaseYear: "Buraxılış İli:",
    materialLabel: "Material:",
    similarProducts: "Oxşar Məhsullar",
    // Auth
    loginTitle: "Giriş",
    loginSubtitle: "Hesabınıza daxil olun",
    signupTitle: "Qeydiyyat",
    signupSubtitle: "Yeni hesab yaradın",
    nameLabel: "Ad",
    passwordLabel: "Şifrə",
    confirmPasswordLabel: "Şifrəni təsdiqləyin",
    pleaseWait: "Gözləyin...",
    signInBtn: "Daxil ol",
    signUpBtn: "Qeydiyyatdan keç",
    orWord: "və ya",
    googleSignIn: "Google ilə daxil ol",
    googleSignUp: "Google ilə qeydiyyatdan keç",
    noAccountQ: "Hesabınız yoxdur?",
    signUpLink: "Qeydiyyatdan keçin",
    haveAccountQ: "Artıq hesabınız var?",
    signInLink: "Daxil olun",
    loginFailed: "Giriş uğursuz oldu: ",
    googleLoginFailed: "Google ilə giriş uğursuz oldu: ",
    signupFailed: "Qeydiyyat uğursuz oldu: ",
    googleSignupFailed: "Google ilə qeydiyyat uğursuz oldu: ",
    passwordsMismatch: "Şifrələr uyğun gəlmir",
    passwordTooShort: "Şifrə ən azı 6 simvoldan ibarət olmalıdır",
    emailInUse: "Bu email artıq istifadə olunur",
    weakPassword: "Şifrə çox zəifdir",
    invalidEmail: "Yanlış email formatı",
    account: "Hesab",
    accountSubtitle: "Profilinizi, ünvanlarınızı və kartlarınızı idarə edin",
    profile: "Profil",
    username: "İstifadəçi adı",
    addresses: "Ünvanlar",
    addAddress: "Ünvan əlavə et",
    addressLabel: "Başlıq (məs. Ev, İş)",
    addressText: "Tam ünvan",
    noAddresses: "Heç bir ünvan əlavə edilməyib",
    paymentMethods: "Ödəniş kartları",
    addCard: "Kart əlavə et",
    cardHolder: "Kart sahibi",
    cardLast4: "Kartın son 4 rəqəmi",
    cardExpiry: "Bitmə tarixi (AA/İİ)",
    cardBrand: "Kart növü",
    noCards: "Heç bir kart əlavə edilməyib",
    cardSecurityNote: "Təhlükəsizlik üçün tam kart nömrəsi saxlanılmır — ödəniş kassada aparılır.",
    myOrders: "Sifarişlərim",
    noOrders: "Hazırda heç bir sifariş yoxdur",
    save: "Yadda saxla",
    cancel: "Ləğv et",
    removeItem: "Sil",
    savedToast: "Yadda saxlanıldı ✓",
    signedInAs: "Daxil olub:",
  },
  en: {
    settings: "Settings",
    customize: "Customize appearance and interface",
    vinylSettings: "Vinyl Settings",
    hideVinylAll: "Hide vinyl entirely",
    hideVinylArtist: "Hide only on Artist page",
    contentView: "Content View",
    biggerText: "Bigger Text",
    biggerCursor: "Bigger Cursor",
    lineHeight: "Line Height",
    lineNormal: "Normal",
    lineRelaxed: "Relaxed",
    lineLoose: "Loose",
    effectsColors: "Effects & Colors",
    stopAnimations: "Stop Animations",
    invertColors: "Invert Colors",
    brightness: "Brightness",
    contrast: "Contrast",
    language: "Language",
    theme: "Theme",
    dark: "Dark",
    light: "Light",
    reset: "Reset Settings",
    addToCart: "Add to Cart",
    back: "Back",
    description: "Description",
    tracklist: "Tracklist",
    reviews: "Reviews & Questions",
    genre: "Genre",
    selectDesign: "Select Design",
    selected: "Selected",
    quantity: "Quantity",
    notFound: "Album Not Found",
    backHome: "Back to Home",
    images: "Images",
    imageNotLoaded: "Image failed to load",
    animated: "Animated",
    static: "Static",
    submitReview: "Submit",
    submitQuestion: "Send Question",
    writeReview: "Write your review...",
    writeQuestion: "Write your question...",
    leaveReview: "Leave a Review",
    askQuestion: "Ask a Question",
    reply: "Reply",
    replyPlaceholder: "Your reply...",
    send: "Send",
    // Nav
    navNew: "New Arrivals",
    navGenres: "Genres",
    navOrders: "Orders",
    navAbout: "About Us",
    // Hero
    heroTag: "Premium Vinyl Collection",
    heroNew: "NEW!",
    heroDesc: '"xperiment" is the new studio album by American rapper and singer Ken Carson.',
    shopNow: "Shop Now",
    listenPreview: "Listen Preview",
    statVinyl: "Vinyl",
    statRare: "Rare Pressings",
    statGenres: "Genres",
    // Featured albums
    newThisWeek: "New This Week",
    featuredRecords: "Featured Records",
    viewAllCollection: "View All Collection",
    newBadge: "NEW",
    // Genre section
    explore: "Explore",
    browseByGenre: "Browse by Genre",
    recordsWord: "records",
    // Merch promo
    officialMerch: "Official Merch",
    merchSubtitle: "Artist apparel and collectibles",
    merchStore: "Merch Store",
    exclusiveMerch: "Exclusive Merch Collections",
    merchCtaSubtitle: "Original apparel and accessories from your favorite artists",
    buyNow: "Buy Now",
    // Accessories
    accessoriesTitle: "Equipment & Accessories",
    accessoriesSubtitle: "Everything for your vinyl collection",
    viewAll: "View All",
    outOfStock: "Out of Stock",
    catAll: "All",
    catTurntable: "Turntables",
    catCdPlayer: "CD Players",
    catStorage: "Storage",
    catCleaning: "Cleaning",
    catAccessories: "Accessories",
    // Newsletter
    newsletterTag: "Stay in the loop",
    newsletterTitle: "Join the Backrooms newsletter",
    newsletterSubtitle: "Get exclusive access to new releases, rare finds and special discounts — no spam.",
    emailPlaceholder: "Enter your email",
    subscribe: "Subscribe",
    newsletterNote: "Join 10,000+ vinyl subscribers already in the club",
    // Footer
    footerShop: "Shop",
    footerGenres: "Genres",
    footerSupport: "Support",
    footerCompany: "Company",
    footerNewArrivals: "New Arrivals",
    footerBestSellers: "Best Sellers",
    footerPreOrders: "Pre-Orders",
    footerSale: "Sale",
    footerContact: "Contact Us",
    footerShipping: "Shipping Info",
    footerReturns: "Returns",
    footerFaq: "FAQ",
    footerAbout: "About Us",
    footerCareers: "Careers",
    footerBlog: "Blog",
    footerTagline: "Your destination for premium vinyl records. Experience music the way it was meant to be heard.",
    footerRights: "© 2026 Backrooms. All rights reserved.",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    // Cart
    cart: "Cart",
    cartEmpty: "Your cart is empty",
    viewCart: "View Cart",
    maxQuantityReached: "Maximum 4 of the same product per order",
    quantityLimitNote: "Limit of 4 per product per customer",
    orderSummary: "Order Summary",
    total: "Total:",
    checkout: "Checkout",
    continueShopping: "Continue shopping",
    // Album page
    selectDesignWarning: "⚠️ Please select a design",
    tracklistLoading: "Loading tracklist...",
    tracklistUnavailable: "Tracklist is currently unavailable.",
    productUnavailable: "This product isn't available for online purchase yet",
    subscribedToast: "Subscribed! ✓",
    adding: "Adding...",
    addedToCart: "Added to cart! ✓",
    errorTryAgain: "An error occurred. Please try again.",
    shopifyIdMissing: "Shopify product ID not found",
    recommendedProducts: "Recommended Products",
    // Collections
    allCollection: "All Collection",
    discoverRecords: "vinyl records to discover",
    filterByGenre: "Filter by Genre:",
    filterByYear: "Filter by Year:",
    filterByArtist: "Filter by Artist:",
    sortByPrice: "Sort by Price:",
    all: "All",
    sortNone: "None",
    sortCheap: "Cheapest → Most Expensive",
    sortExpensive: "Most Expensive → Cheapest",
    // Artist page
    artistNotFound: "Artist Not Found",
    latestRelease: "Latest Release",
    discography: "Discography",
    music: "Music",
    // Search
    searchPlaceholder: "Search albums, artists or genres...",
    searchPlaceholderShort: "Search albums or artists...",
    resultsFor: 'Results for "{query}"',
    allAlbums: "All albums",
    resultsWord: "results",
    noResults: "No results found",
    tryDifferent: "Try a different keyword or genre",
    similarGenres: "Similar genres",
    viewAllResults: "View all results →",
    // Favorites
    loading: "Loading...",
    favoritesTitle: "Favorites",
    albumsWord: "albums",
    noFavoritesYet: "No favorites yet",
    addFavoritesHint: "Add albums you love to your favorites",
    // User menu
    orders: "Orders",
    logout: "Log Out",
    close: "Close",
    // 404
    pageNotFound: "Oops! Page not found",
    // Merch collections page
    merchCollection: "Merch Collection",
    categoriesWord: "categories",
    artistsWord: "artists",
    productsFound: "products found",
    backToCategories: "Back to categories",
    productsWord: "Products",
    viewCollection: "View Collection",
    moreWord: "more",
    filters: "Filters",
    clear: "Clear",
    artistLabel: "Artist",
    yearLabel: "Year",
    sortLabel: "Sort",
    sortDefault: "Default",
    priceLowHigh: "Price: Low to High",
    priceHighLow: "Price: High to Low",
    yearNewOld: "Year: New to Old",
    yearOldNew: "Year: Old to New",
    noProductsFound: "No products found",
    clearFilters: "Clear Filters",
    // Merch product page
    productNotFound: "Product Not Found",
    backToMerch: "← Back to merch",
    selectSize: "Select Size",
    selectSizeWarning: "⚠️ Please select a size",
    colorLabel: "Color",
    productDetails: "Product Details",
    categoryLabel: "Category:",
    releaseYear: "Release Year:",
    materialLabel: "Material:",
    similarProducts: "Similar Products",
    // Auth
    loginTitle: "Log In",
    loginSubtitle: "Sign in to your account",
    signupTitle: "Sign Up",
    signupSubtitle: "Create a new account",
    nameLabel: "Name",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    pleaseWait: "Please wait...",
    signInBtn: "Sign In",
    signUpBtn: "Sign Up",
    orWord: "or",
    googleSignIn: "Sign in with Google",
    googleSignUp: "Sign up with Google",
    noAccountQ: "Don't have an account?",
    signUpLink: "Sign up",
    haveAccountQ: "Already have an account?",
    signInLink: "Sign in",
    loginFailed: "Login failed: ",
    googleLoginFailed: "Google sign-in failed: ",
    signupFailed: "Sign-up failed: ",
    googleSignupFailed: "Google sign-up failed: ",
    passwordsMismatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    emailInUse: "This email is already in use",
    weakPassword: "Password is too weak",
    invalidEmail: "Invalid email format",
    account: "Account",
    accountSubtitle: "Manage your profile, addresses and cards",
    profile: "Profile",
    username: "Username",
    addresses: "Addresses",
    addAddress: "Add Address",
    addressLabel: "Label (e.g. Home, Work)",
    addressText: "Full address",
    noAddresses: "No addresses added yet",
    paymentMethods: "Payment Cards",
    addCard: "Add Card",
    cardHolder: "Cardholder name",
    cardLast4: "Last 4 digits",
    cardExpiry: "Expiry (MM/YY)",
    cardBrand: "Card type",
    noCards: "No cards added yet",
    cardSecurityNote: "For security, full card numbers are never stored — payment happens at checkout.",
    myOrders: "My Orders",
    noOrders: "No orders yet",
    save: "Save",
    cancel: "Cancel",
    removeItem: "Remove",
    savedToast: "Saved ✓",
    signedInAs: "Signed in as",
  },
  ru: {
    settings: "Настройки",
    customize: "Настройте внешний вид и интерфейс",
    vinylSettings: "Настройки виниловой пластинки",
    hideVinylAll: "Скрыть полностью",
    hideVinylArtist: "Скрыть только на странице исполнителя",
    contentView: "Внешний вид контента",
    biggerText: "Крупный текст",
    biggerCursor: "Крупный курсор",
    lineHeight: "Межстрочный интервал",
    lineNormal: "Нормальный",
    lineRelaxed: "Удобный",
    lineLoose: "Широкий",
    effectsColors: "Эффекты и цвета",
    stopAnimations: "Остановить анимации",
    invertColors: "Инвертировать цвета",
    brightness: "Яркость",
    contrast: "Контрастность",
    language: "Язык",
    theme: "Тема",
    dark: "Тёмная",
    light: "Светлая",
    reset: "Сбросить настройки",
    addToCart: "Добавить в корзину",
    back: "Назад",
    description: "Описание",
    tracklist: "Список треков",
    reviews: "Отзывы и вопросы",
    genre: "Жанр",
    selectDesign: "Выбрать дизайн",
    selected: "Выбрано",
    quantity: "Количество",
    notFound: "Альбом не найден",
    backHome: "На главную",
    images: "Фотографии",
    imageNotLoaded: "Не удалось загрузить фото",
    animated: "Анимация",
    static: "Статичный",
    submitReview: "Отправить",
    submitQuestion: "Отправить вопрос",
    writeReview: "Напишите отзыв...",
    writeQuestion: "Напишите вопрос...",
    leaveReview: "Оставить отзыв",
    askQuestion: "Задать вопрос",
    reply: "Ответить",
    replyPlaceholder: "Ваш ответ...",
    send: "Отправить",
    // Nav
    navNew: "Новинки",
    navGenres: "Жанры",
    navOrders: "Заказы",
    navAbout: "О нас",
    // Hero
    heroTag: "Премиальная коллекция винила",
    heroNew: "НОВИНКА!",
    heroDesc: "«xperiment» — новый студийный альбом американского рэпера и певца Ken Carson.",
    shopNow: "Купить сейчас",
    listenPreview: "Прослушать превью",
    statVinyl: "Винил",
    statRare: "Редкие издания",
    statGenres: "Жанры",
    // Featured albums
    newThisWeek: "Новое на этой неделе",
    featuredRecords: "Избранные записи",
    viewAllCollection: "Смотреть всю коллекцию",
    newBadge: "НОВИНКА",
    // Genre section
    explore: "Исследуйте",
    browseByGenre: "Поиск по жанру",
    recordsWord: "записей",
    // Merch promo
    officialMerch: "Официальный мерч",
    merchSubtitle: "Одежда артистов и коллекционные предметы",
    merchStore: "Магазин мерча",
    exclusiveMerch: "Эксклюзивные коллекции мерча",
    merchCtaSubtitle: "Оригинальная одежда и аксессуары от любимых артистов",
    buyNow: "Купить",
    // Accessories
    accessoriesTitle: "Оборудование и аксессуары",
    accessoriesSubtitle: "Всё для вашей коллекции винила",
    viewAll: "Смотреть все",
    outOfStock: "Нет в наличии",
    catAll: "Все",
    catTurntable: "Проигрыватели",
    catCdPlayer: "CD-плееры",
    catStorage: "Хранение",
    catCleaning: "Чистка",
    catAccessories: "Аксессуары",
    // Newsletter
    newsletterTag: "Будьте в курсе новинок",
    newsletterTitle: "Подпишитесь на рассылку Backrooms",
    newsletterSubtitle: "Эксклюзивный доступ к новым релизам, редким находкам и специальным скидкам — без спама.",
    emailPlaceholder: "Введите email",
    subscribe: "Подписаться",
    newsletterNote: "Присоединяйтесь к 10 000+ подписчикам клуба",
    // Footer
    footerShop: "Магазин",
    footerGenres: "Жанры",
    footerSupport: "Поддержка",
    footerCompany: "Компания",
    footerNewArrivals: "Новинки",
    footerBestSellers: "Бестселлеры",
    footerPreOrders: "Предзаказы",
    footerSale: "Распродажа",
    footerContact: "Связаться с нами",
    footerShipping: "Информация о доставке",
    footerReturns: "Возвраты",
    footerFaq: "Частые вопросы",
    footerAbout: "О нас",
    footerCareers: "Карьера",
    footerBlog: "Блог",
    footerTagline: "Ваше место для премиальных виниловых пластинок. Слушайте музыку так, как она была задумана.",
    footerRights: "© 2026 Backrooms. Все права защищены.",
    privacyPolicy: "Политика конфиденциальности",
    termsOfService: "Условия использования",
    // Cart
    cart: "Корзина",
    cartEmpty: "Корзина пуста",
    viewCart: "Перейти в корзину",
    maxQuantityReached: "Не более 4 штук одного товара в заказе",
    quantityLimitNote: "Лимит: не более 4 штук одного товара на покупателя",
    orderSummary: "Сводка заказа",
    total: "Итого:",
    checkout: "Оформить заказ",
    continueShopping: "Продолжить покупки",
    // Album page
    selectDesignWarning: "⚠️ Пожалуйста, выберите дизайн",
    tracklistLoading: "Загрузка списка треков...",
    tracklistUnavailable: "Список треков временно недоступен.",
    productUnavailable: "Этот товар пока недоступен для онлайн-покупки",
    subscribedToast: "Вы подписались! ✓",
    adding: "Добавление...",
    addedToCart: "Добавлено в корзину! ✓",
    errorTryAgain: "Произошла ошибка. Попробуйте снова.",
    shopifyIdMissing: "ID товара Shopify не найден",
    recommendedProducts: "Рекомендуемые товары",
    // Collections
    allCollection: "Вся коллекция",
    discoverRecords: "виниловых пластинок ждут вас",
    filterByGenre: "Фильтр по жанру:",
    filterByYear: "Фильтр по году:",
    filterByArtist: "Фильтр по исполнителю:",
    sortByPrice: "Сортировка по цене:",
    all: "Все",
    sortNone: "Без сортировки",
    sortCheap: "Сначала дешёвые",
    sortExpensive: "Сначала дорогие",
    // Artist page
    artistNotFound: "Исполнитель не найден",
    latestRelease: "Последний релиз",
    discography: "Дискография",
    music: "Музыка",
    // Search
    searchPlaceholder: "Поиск альбома, исполнителя или жанра...",
    searchPlaceholderShort: "Поиск альбома или исполнителя...",
    resultsFor: 'Результаты для "{query}"',
    allAlbums: "Все альбомы",
    resultsWord: "результатов",
    noResults: "Ничего не найдено",
    tryDifferent: "Попробуйте другое слово или жанр",
    similarGenres: "Похожие жанры",
    viewAllResults: "Все результаты →",
    // Favorites
    loading: "Загрузка...",
    favoritesTitle: "Избранное",
    albumsWord: "альбомов",
    noFavoritesYet: "Пока нет избранного",
    addFavoritesHint: "Добавляйте понравившиеся альбомы в избранное",
    // User menu
    orders: "Заказы",
    logout: "Выйти",
    close: "Закрыть",
    // 404
    pageNotFound: "Упс! Страница не найдена",
    // Merch collections page
    merchCollection: "Коллекция мерча",
    categoriesWord: "категорий",
    artistsWord: "исполнителей",
    productsFound: "товаров найдено",
    backToCategories: "Назад к категориям",
    productsWord: "Товаров",
    viewCollection: "Смотреть коллекцию",
    moreWord: "ещё",
    filters: "Фильтры",
    clear: "Очистить",
    artistLabel: "Исполнитель",
    yearLabel: "Год",
    sortLabel: "Сортировка",
    sortDefault: "По умолчанию",
    priceLowHigh: "Цена: по возрастанию",
    priceHighLow: "Цена: по убыванию",
    yearNewOld: "Год: сначала новые",
    yearOldNew: "Год: сначала старые",
    noProductsFound: "Товары не найдены",
    clearFilters: "Очистить фильтры",
    // Merch product page
    productNotFound: "Товар не найден",
    backToMerch: "← Назад к мерчу",
    selectSize: "Выберите размер",
    selectSizeWarning: "⚠️ Пожалуйста, выберите размер",
    colorLabel: "Цвет",
    productDetails: "Информация о товаре",
    categoryLabel: "Категория:",
    releaseYear: "Год выпуска:",
    materialLabel: "Материал:",
    similarProducts: "Похожие товары",
    // Auth
    loginTitle: "Вход",
    loginSubtitle: "Войдите в свой аккаунт",
    signupTitle: "Регистрация",
    signupSubtitle: "Создайте новый аккаунт",
    nameLabel: "Имя",
    passwordLabel: "Пароль",
    confirmPasswordLabel: "Подтвердите пароль",
    pleaseWait: "Подождите...",
    signInBtn: "Войти",
    signUpBtn: "Зарегистрироваться",
    orWord: "или",
    googleSignIn: "Войти через Google",
    googleSignUp: "Регистрация через Google",
    noAccountQ: "Нет аккаунта?",
    signUpLink: "Зарегистрируйтесь",
    haveAccountQ: "Уже есть аккаунт?",
    signInLink: "Войдите",
    loginFailed: "Не удалось войти: ",
    googleLoginFailed: "Не удалось войти через Google: ",
    signupFailed: "Регистрация не удалась: ",
    googleSignupFailed: "Регистрация через Google не удалась: ",
    passwordsMismatch: "Пароли не совпадают",
    passwordTooShort: "Пароль должен содержать минимум 6 символов",
    emailInUse: "Этот email уже используется",
    weakPassword: "Слишком слабый пароль",
    invalidEmail: "Неверный формат email",
    account: "Аккаунт",
    accountSubtitle: "Управляйте профилем, адресами и картами",
    profile: "Профиль",
    username: "Имя пользователя",
    addresses: "Адреса",
    addAddress: "Добавить адрес",
    addressLabel: "Название (напр. Дом, Работа)",
    addressText: "Полный адрес",
    noAddresses: "Адреса пока не добавлены",
    paymentMethods: "Платёжные карты",
    addCard: "Добавить карту",
    cardHolder: "Имя владельца карты",
    cardLast4: "Последние 4 цифры",
    cardExpiry: "Срок действия (ММ/ГГ)",
    cardBrand: "Тип карты",
    noCards: "Карты пока не добавлены",
    cardSecurityNote: "В целях безопасности полный номер карты не хранится — оплата происходит при оформлении заказа.",
    myOrders: "Мои заказы",
    noOrders: "Заказов пока нет",
    save: "Сохранить",
    cancel: "Отмена",
    removeItem: "Удалить",
    savedToast: "Сохранено ✓",
    signedInAs: "Вы вошли как",
  }
};

// Returns the right variant of a translatable data field.
// Accepts either a plain string (returned unchanged) or an object like
// { az: "...", en: "...", ru: "..." } — falls back to az, then to any value.
export const localizeText = (value, language) => {
  if (value && typeof value === "object") {
    return value[language] || value.az || Object.values(value)[0] || "";
  }
  return value;
};

// --- Localization of catalog date/duration strings ------------------------
// Catalog data stores dates like "24 Noyabr 2008" and durations like
// "12 mahnı, 52 dəqiqə" (the formats the Spotify fetcher also produces).
// These helpers translate those patterns on the fly, and also accept
// hand-written { az, en, ru } objects like descriptions do.

const AZ_MONTHS = ["yanvar", "fevral", "mart", "aprel", "may", "iyun", "iyul", "avqust", "sentyabr", "oktyabr", "noyabr", "dekabr"];
const EN_MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const RU_MONTHS = ["января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря"];

// Azerbaijani "İ" lowercases to "i" + combining dot — normalize that away
const azFold = (s) => s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "");

const ruPlural = (n, one, few, many) => {
  const mod10 = n % 10, mod100 = n % 100;
  if (mod10 === 1 && mod100 !== 11) return one;
  if (mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)) return few;
  return many;
};

export const localizeReleaseDate = (value, language) => {
  if (value && typeof value === "object") return localizeText(value, language);
  if (!value || language === "az") return value;
  const m = String(value).trim().match(/^(\d{1,2})\s+(\S+)\s+(\d{4})$/);
  if (!m) return value;
  const idx = AZ_MONTHS.indexOf(azFold(m[2]));
  if (idx === -1) return value;
  const day = parseInt(m[1], 10), year = m[3];
  if (language === "en") return `${EN_MONTHS[idx]} ${day}, ${year}`;
  if (language === "ru") return `${day} ${RU_MONTHS[idx]} ${year}`;
  return value;
};

export const localizeDuration = (value, language) => {
  if (value && typeof value === "object") return localizeText(value, language);
  if (!value || language === "az") return value;
  const str = String(value).trim();

  const full = str.match(/^(\d+)\s*mahnı(?:lar)?\s*,\s*(\d+)\s*dəqiqə$/i);
  if (full) {
    const songs = parseInt(full[1], 10), mins = parseInt(full[2], 10);
    if (language === "en") {
      return `${songs} ${songs === 1 ? "song" : "songs"}, ${mins} ${mins === 1 ? "minute" : "minutes"}`;
    }
    if (language === "ru") {
      return `${songs} ${ruPlural(songs, "песня", "песни", "песен")}, ${mins} ${ruPlural(mins, "минута", "минуты", "минут")}`;
    }
  }

  const minsOnly = str.match(/^(\d+)\s*dəqiqə$/i);
  if (minsOnly) {
    const mins = parseInt(minsOnly[1], 10);
    if (language === "en") return `${mins} ${mins === 1 ? "minute" : "minutes"}`;
    if (language === "ru") return `${mins} ${ruPlural(mins, "минута", "минуты", "минут")}`;
  }

  return value;
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("userSettings");
    if (saved) {
      try {
        return JSON.parse(saved).language || "az";
      } catch { return "az"; }
    }
    return "az";
  });

  useEffect(() => {
    document.documentElement.setAttribute("lang", language);
  }, [language]);

  const t = translations[language] || translations.az;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
};
